config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "dashboard#index"

  resources :facebook_apps do
    resources :monitor_tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/facebook_app.rb
# == Schema Information
#
# Table name: facebook_apps
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  app_id     :string           not null
#  app_secret :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  page_url   :string
#

class FacebookApp < ApplicationRecord
  has_many :monitor_tasks, dependent: :destroy
end

app/models/monitor_task.rb
# == Schema Information
#
# Table name: monitor_tasks
#
#  id                        :bigint(8)        not null, primary key
#  facebook_app_id           :integer          not null
#  source_facebook_url       :string           not null
#  last_posted_facebook_id   :string
#  last_posted_facebook_time :datetime
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#

class MonitorTask < ApplicationRecord
  belongs_to :facebook_app
  has_many :monitor_task_histories, dependent: :destroy
end

app/models/monitor_task_history.rb
# == Schema Information
#
# Table name: monitor_task_histories
#
#  id                        :bigint(8)        not null, primary key
#  monitor_task_id           :integer          not null
#  last_posted_facebook_id   :string
#  last_posted_facebook_time :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#

class MonitorTaskHistory < ApplicationRecord
  belongs_to :monitor_task
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/facebook_apps_controller.rb
class FacebookAppsController < ApplicationController
  before_action :find_facebook_app, only: [:edit, :destroy, :update]

  def index
    @facebook_apps = FacebookApp.all
  end

  def new
    @facebook_app = FacebookApp.new
  end

  def create
    @facebook_app = FacebookApp.new(facebook_app_params)

    if @facebook_app.save
      flash[:success] = "Created new facebook app."
      redirect_to facebook_apps_path
    else
      flash[:alert] = @facebook_app.errors.full_messages.join
      render :new
    end
  end

  def edit
  end

  def update
    @facebook_app.update_attributes(facebook_app_params)
    flash[:success] = "Updated facebook app."
    redirect_to facebook_apps_path
  end

  def destroy
    @facebook_app.destroy
    flash[:success] = "Deleted facebook app."
    redirect_to facebook_apps_path
  end

  private

  def find_facebook_app
    @facebook_app = FacebookApp.find(params[:id])
  end

  def facebook_app_params
    params.require(:facebook_app)
          .permit(:name, :app_id, :app_secret, :page_url)
  end
end

app/controllers/monitor_tasks_controller.rb
class MonitorTasksController < ApplicationController
  before_action :find_facebook_app
  before_action :find_monitor_task, only: [:edit, :destroy, :update]

  def index
    @monitor_tasks = @facebook_app.monitor_tasks
  end

  def new
    @monitor_task = @facebook_app.monitor_tasks.new
  end

  def create
    @monitor_task = @facebook_app.monitor_tasks.new(monitor_task_params)

    if @monitor_task.save
      flash[:success] = "Created new monitor task."
      redirect_to facebook_app_monitor_tasks_path(@facebook_app)
    else
      flash[:alert] = @monitor_task.errors.full_messages.join
      render :new
    end
  end

  def edit
  end

  def update
    @monitor_task.update_attributes(monitor_task_params)
    flash[:success] = "Updated monitor task."
    redirect_to facebook_app_monitor_tasks_path(@facebook_app)
  end

  def destroy
    @monitor_task.destroy
    flash[:success] = "Deleted monitor task."
    redirect_to facebook_app_monitor_tasks_path(@facebook_app)
  end

  private

  def find_facebook_app
    @facebook_app = FacebookApp.find(params[:facebook_app_id])
  end

  def find_monitor_task
    @monitor_task = MonitorTask.find(params[:id])
  end

  def monitor_task_params
    params.require(:monitor_task).permit(:source_facebook_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/facebook_apps/_form.html.erb
<%= form_for @facebook_app, html: { class: "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Name", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :app_id, "APP ID", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :app_id, class: "form-control", placeholder: "APP ID", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :app_secret, "APP SECRET", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :app_secret, class: "form-control", placeholder: "APP SECRET", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :page_url, "Page url", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :page_url, class: "form-control", placeholder: "Page url", required: true %>
    </div>
  </div>

  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/facebook_apps/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Facebook App</h5>
      </div>
      <div class="ibox-content">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/facebook_apps/index.html.erb
<div class="text-right">
  <%= link_to "Create Facebook App", new_facebook_app_path, class: "btn btn-primary" %>
</div>
<br/>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>APP ID</th>
      <th>APP SECRET</th>
      <th>Page Url</th>
      <th></th>
    </tr>
  </thead>
  <% @facebook_apps.each do |facebook_app| %>
    <tr>
      <td><%= link_to facebook_app.name, edit_facebook_app_path(facebook_app) %></td>
      <td><%= facebook_app.app_id %></td>
      <td><%= facebook_app.app_secret %></td>
      <td><%= facebook_app.page_url %></td>
      <td>
        <%= link_to "Monitor tasks",
          facebook_app_monitor_tasks_path(facebook_app),
          class: "btn btn-info"
        %>
        <%= link_to "Edit",
          edit_facebook_app_path(facebook_app),
          class: "btn btn-primary"
        %>
        <%= link_to "Delete",
          facebook_app_path(facebook_app),
          class: "btn btn-danger",
          method: :delete,
          data: { confirm: "Are you sure?" }
        %>
      </td>
    </tr>
  <% end %>
</table>

app/views/facebook_apps/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Facebook App</h5>
      </div>
      <div class="ibox-content">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_flash_message.html.erb
<script>
  $(document).ready(function() {
    <% unless flash[:success].blank? %>
      toastr.success("<%= flash[:success] %>")
    <% end %>

    <% unless flash[:danger].blank? %>
      toastr.error("<%= flash[:danger] %>")
    <% end %>

    <% unless flash[:alert].blank? %>
      toastr.error("<%= flash[:alert] %>")
    <% end %>
  })
</script>

app/views/layouts/_topnavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="">Home</a>
      </li>
      <li class="nav-item">
        <%= link_to "Facebook apps", facebook_apps_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Monitor tasks</a>
      </li>
    </ul>
  </div>
  <div>
    <%= link_to destroy_user_session_path, method: 'delete' do %>
      <i class="fa fa-sign-out"></i> Log out
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialMediaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container container-main">
      <%= render "layouts/topnavbar" %>
      <br/>
      <%= yield %>
    </div>

    <%= render "layouts/flash_message" %>
  </body>
</html>

app/views/monitor_tasks/_facebook_app_summary.html.erb
<h4>Facebook app</h4>
<div class="row">
  <div class="col-md-3">App name</div>
  <div class="col-md-9"><%= @facebook_app.name %></div>
</div>
<div class="row">
  <div class="col-md-3">App ID</div>
  <div class="col-md-9"><%= @facebook_app.app_id %></div>
</div>

app/views/monitor_tasks/_form.html.erb
<%= form_for [@facebook_app, @monitor_task], html: { class: "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :source_facebook_url, "Source Facebook Url", class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :source_facebook_url, class: "form-control", placeholder: "Source Facebook Url", required: true %>
    </div>
  </div>

  <div class="hr-line-dashed"></div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-2">
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <%= link_to "Cancel", facebook_app_monitor_tasks_path(@facebook_app), class: "btn btn-info" %>
    </div>
  </div>
<% end %>

app/views/monitor_tasks/edit.html.erb
<%= render "facebook_app_summary" %>
<br/>
<br/>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Monitor Task</h5>
      </div>
      <div class="ibox-content">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/monitor_tasks/index.html.erb
<%= render "facebook_app_summary" %>
<br/>
<br/>

<div class="row">
  <div class="col-md-6">
    <h5>Monitor Tasks</h5>
  </div>
  <div class="col-md-6 text-right">
    <%= link_to "Create Monitor Task", new_facebook_app_monitor_task_path(@facebook_app), class: "btn btn-primary" %>
  </div>
</div>
<br/>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Source Facebook Url</th>
      <th>Last Posted Facebook Id</th>
      <th>Last Posted Facebook Time</th>
      <th></th>
    </tr>
  </thead>
  <% @monitor_tasks.each do |monitor_task| %>
    <tr>
      <td><%= monitor_task.source_facebook_url %></td>
      <td><%= monitor_task.last_posted_facebook_id %></td>
      <td><%= monitor_task.last_posted_facebook_time %></td>
      <td>
        <%= link_to "Edit",
          edit_facebook_app_monitor_task_path(@facebook_app, monitor_task),
          class: "btn btn-primary"
        %>
        <%= link_to "Delete",
          facebook_app_monitor_task_path(@facebook_app, monitor_task),
          class: "btn btn-danger",
          method: :delete,
          data: { confirm: "Are you sure?" }
        %>
      </td>
    </tr>
  <% end %>
</table>

app/views/monitor_tasks/new.html.erb
<%= render "facebook_app_summary" %>
<br/>
<br/>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5>Monitor Task</h5>
      </div>
      <div class="ibox-content">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>